### ISSUE TITLE
Extraire les enums et constantes déclarées à plusieurs endroits en un seul endroit

### ISSUE THREAD

**Issue by SimWalther** [SimWalther/vietnam_coffee_detection#41]
Typiquement, l'enum Bands est présent dans plusieurs notebooks, il serait intéressant de l'importer d'un ficher python.
Les chemins d'accès vers les dossiers de données etc pourraient être centralisés.

**Comment by Waltharnack** [comment]
C'est fait pour Bands

**Comment by SimWalther** [comment]
Je laisse les chemins d'accès tel quel pour le moment
