### ISSUE TITLE
Être capable de visualiser l'évolution d'une série de prédictions dans le temps

### ISSUE THREAD

**Issue by SimWalther** [SimWalther/vietnam_coffee_detection#43]
- Commencer par essayer avec la saison sèche de chaque année
- Réfléchir comment bien afficher ces données (couleur en fonction de la première détection ? Peut-être ne pas faire directement sur une carte mais seulement l'évolution dans le temps ?) Accent sur café / pas café

**Comment by Waltharnack** [comment]
- [x] carte avec couleur différente suivant la première année de détection du café (pour les labels connus)
- [ ] carte avec le nombre de détection totale dans des couleurs différentes avec les labels connus représenté sur la carte

**Comment by SimWalther** [comment]
- [ ] utiliser les données connues de 2017 et comparer par-rapport à celles-là
